export interface Quote {
  text: string
  author: string
}

export const QUOTES: Quote[] = [
  // ── Original quotes ───────────────────────────────────────────────────────
  { text: "You do not rise to the level of your goals. You fall to the level of your systems.", author: "James Clear" },
  { text: "Every action you take is a vote for the type of person you wish to become.", author: "James Clear" },
  { text: "Success is the product of daily habits — not once-in-a-lifetime transformations.", author: "James Clear" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle" },
  { text: "Small daily improvements are the key to staggering long-term results.", author: "Robin Sharma" },
  { text: "The first wealth is health.", author: "Ralph Waldo Emerson" },
  { text: "Take care of your body. It's the only place you have to live.", author: "Jim Rohn" },
  { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
  { text: "We must all suffer from one of two pains: the pain of discipline or the pain of regret.", author: "Jim Rohn" },
  { text: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun" },
  { text: "The groundwork of all happiness is health.", author: "Leigh Hunt" },
  { text: "The greatest wealth is health.", author: "Virgil" },
  { text: "Health is not valued until sickness comes.", author: "Thomas Fuller" },
  { text: "Health is like money — we never have a true idea of its value until we lose it.", author: "Josh Billings" },
  { text: "A healthy outside starts from the inside.", author: "Robert Urich" },
  { text: "To keep the body in good health is a duty, otherwise we shall not be able to keep our mind strong and clear.", author: "Buddha" },
  { text: "Your health is an investment, not an expense.", author: "Unknown" },
  { text: "Physical fitness is not only one of the most important keys to a healthy body, it is the basis of dynamic and creative intellectual activity.", author: "John F. Kennedy" },
  { text: "Physical fitness is the basis of all other forms of excellence.", author: "John F. Kennedy" },
  { text: "What gets measured gets managed.", author: "Peter Drucker" },
  { text: "Without data, you're just another person with an opinion.", author: "W. Edwards Deming" },
  { text: "Continuous improvement is better than delayed perfection.", author: "Mark Twain" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "Measure what is measurable, and make measurable what is not so.", author: "Galileo Galilei" },
  { text: "I hated every minute of training, but I said, 'Don't quit. Suffer now and live the rest of your life as a champion.'", author: "Muhammad Ali" },
  { text: "Champions aren't made in gyms. Champions are made from something they have deep inside them.", author: "Muhammad Ali" },
  { text: "The fight is won or lost far away from witnesses — behind the lines, in the gym, and out there on the road.", author: "Muhammad Ali" },
  { text: "Float like a butterfly, sting like a bee.", author: "Muhammad Ali" },
  { text: "If you always put limits on everything you do, physical or anything else, it will spread into your work and into your life. There are no limits. There are only plateaus.", author: "Bruce Lee" },
  { text: "Do not pray for an easy life, pray for the strength to endure a difficult one.", author: "Bruce Lee" },
  { text: "The successful warrior is the average man, with laser-like focus.", author: "Bruce Lee" },
  { text: "Be water, my friend.", author: "Bruce Lee" },
  { text: "The last three or four reps is what makes the muscle grow. This area of pain divides a champion from someone who is not a champion.", author: "Arnold Schwarzenegger" },
  { text: "The mind is the limit. As long as the mind can envision the fact that you can do something, you can do it.", author: "Arnold Schwarzenegger" },
  { text: "I've missed more than 9,000 shots in my career. I've failed over and over again in my life. And that is why I succeed.", author: "Michael Jordan" },
  { text: "Some people want it to happen, some wish it would happen, others make it happen.", author: "Michael Jordan" },
  { text: "You must expect great things of yourself before you can do them.", author: "Michael Jordan" },
  { text: "Obstacles don't have to stop you. If you run into a wall, don't turn around and give up.", author: "Michael Jordan" },
  { text: "Hard work beats talent when talent doesn't work hard.", author: "Tim Notke" },
  { text: "Success is never owned. It is only rented, and the rent is due every day.", author: "Rory Vaden" },
  { text: "If it doesn't challenge you, it doesn't change you.", author: "Fred DeVito" },
  { text: "It's not whether you get knocked down, it's whether you get up.", author: "Vince Lombardi" },
  { text: "Winners never quit and quitters never win.", author: "Vince Lombardi" },
  { text: "Make each day your masterpiece.", author: "John Wooden" },
  { text: "Success is not final; failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { text: "If you're going through hell, keep going.", author: "Winston Churchill" },
  { text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
  { text: "Well done is better than well said.", author: "Benjamin Franklin" },
  { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
  { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { text: "Do not wait; the time will never be 'just right.' Start where you stand.", author: "Napoleon Hill" },
  { text: "Strength does not come from physical capacity. It comes from an indomitable will.", author: "Mahatma Gandhi" },
  { text: "The more you sweat in training, the less you bleed in battle.", author: "Richard Marcinko" },
  { text: "Ability is what you're capable of doing. Motivation determines what you do. Attitude determines how well you do it.", author: "Lou Holtz" },
  { text: "To enjoy the glow of good health, you must exercise.", author: "Gene Tunney" },
  { text: "Tough times never last, but tough people do.", author: "Robert H. Schuller" },
  { text: "In training, you listen to your body. In competition, you tell your body to shut up.", author: "Rich Froning" },
  { text: "You have to push past your perceived limits, push past that point you thought was as far as you can go.", author: "Drew Brees" },
  { text: "Strength is not just about lifting weights. It's about lifting yourself up every single day.", author: "Unknown" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { text: "Strive for progress, not perfection.", author: "Unknown" },
  { text: "A year from now you'll wish you had started today.", author: "Karen Lamb" },
  { text: "Your body can stand almost anything. It's your mind that you have to convince.", author: "Unknown" },
  { text: "The only bad workout is the one that didn't happen.", author: "Unknown" },
  { text: "Results happen over time, not overnight. Work hard, stay consistent, and be patient.", author: "Unknown" },
  { text: "You're only one workout away from a good mood.", author: "Unknown" },
  { text: "Do something today that your future self will thank you for.", author: "Sean Patrick Flanery" },
  { text: "The body achieves what the mind believes.", author: "Unknown" },
  { text: "The pain you feel today will be the strength you feel tomorrow.", author: "Unknown" },
  { text: "One rep at a time. One session at a time. One day at a time.", author: "Unknown" },
  { text: "It never gets easier. You just get better.", author: "Unknown" },
  { text: "The first step to getting somewhere is to decide you're not going to stay where you are.", author: "J.P. Morgan" },
  { text: "We become what we think about most of the time.", author: "Earl Nightingale" },
  { text: "Showing up today is already a win.", author: "Unknown" },
  { text: "The secret is not to sprint and rest. It's to pace yourself and keep going.", author: "Unknown" },
  { text: "Be patient with yourself. Self-growth is tender; it's holy ground.", author: "Stephen Covey" },
  { text: "You don't always get what you wish for. You get what you work for.", author: "Unknown" },
  { text: "Pain is temporary. Quitting lasts forever.", author: "Lance Armstrong" },
  { text: "If something stands between you and your success, move it. Never be denied.", author: "Dwayne Johnson" },
  { text: "Wake up determined. Go to bed satisfied.", author: "Dwayne Johnson" },
  { text: "Blood, sweat, and respect. First two you give. Last one you earn.", author: "Dwayne Johnson" },
  { text: "Success isn't always about greatness. It's about consistency.", author: "Dwayne Johnson" },
  { text: "You have to remember something: everybody pities the weak; jealousy you have to earn.", author: "Arnold Schwarzenegger" },
  { text: "For me, life is continuously being hungry. The meaning of life is not simply to exist, to survive, but to move ahead.", author: "Arnold Schwarzenegger" },
  { text: "I don't stop when I'm tired. I stop when I'm done.", author: "David Goggins" },
  { text: "The most important conversation is the one you have with yourself.", author: "David Goggins" },
  { text: "You are in danger of living a life so comfortable and soft that you will die without ever realizing your true potential.", author: "David Goggins" },
  { text: "Suffer the pain of discipline or suffer the pain of regret.", author: "David Goggins" },
  { text: "Waste no more time arguing about what a good man should be. Be one.", author: "Marcus Aurelius" },
  { text: "You have power over your mind — not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius" },
  { text: "The impediment to action advances action. What stands in the way becomes the way.", author: "Marcus Aurelius" },
  { text: "Confine yourself to the present.", author: "Marcus Aurelius" },
  { text: "The quality of your practice is ultimately measured by its effect on the quality of your life.", author: "Unknown" },
  { text: "Champions do not become champions when they win the event, but in the hours, weeks, months and years they spend preparing for it.", author: "T. Alan Armstrong" },
  { text: "There are no shortcuts. The fact that a shortcut is important to you means that the outcome is more important to you than the journey.", author: "Unknown" },
  { text: "Obsessed is a word the lazy use to describe the dedicated.", author: "Unknown" },
  { text: "Train like an athlete, eat like a nutritionist, sleep like a baby, win like a champion.", author: "Unknown" },
  { text: "Your future self is watching you right now through your memories. Make it worth watching.", author: "Aubrey de Grey" },
  { text: "Don't wish it were easier. Wish you were better.", author: "Jim Rohn" },
  { text: "The difference between who you are and who you want to be is what you do.", author: "Unknown" },
  { text: "Eighty percent of success is showing up.", author: "Woody Allen" },

  // ── 100 new philosophical quotes: health = wealth ─────────────────────────
  { text: "He who has health has hope; and he who has hope has everything.", author: "Arabian Proverb" },
  { text: "It is health that is real wealth and not pieces of gold and silver.", author: "Mahatma Gandhi" },
  { text: "A sound mind in a sound body is a short but full description of a happy state in this world.", author: "John Locke" },
  { text: "The body is the temple of the soul.", author: "Hippocrates" },
  { text: "Let food be thy medicine and medicine be thy food.", author: "Hippocrates" },
  { text: "Walking is the best medicine.", author: "Hippocrates" },
  { text: "The natural healing force within each one of us is the greatest force in getting well.", author: "Hippocrates" },
  { text: "Look to the nervous system as the key to maximum health.", author: "Galen" },
  { text: "Those who think they have no time for healthy eating will sooner or later have to find time for illness.", author: "Edward Stanley" },
  { text: "Lack of activity destroys the good condition of every human being, while movement and methodical physical exercise save it and preserve it.", author: "Plato" },
  { text: "In order for man to succeed in life, God provided him with two means: education and physical activity. Not separately, one for the soul and the other for the body, but for the two together.", author: "Plato" },
  { text: "The human body is the best picture of the human soul.", author: "Ludwig Wittgenstein" },
  { text: "Our bodies are our gardens; our wills are our gardeners.", author: "William Shakespeare" },
  { text: "Health is the condition of wisdom, and the sign is cheerfulness — an open and noble temper.", author: "Ralph Waldo Emerson" },
  { text: "The body is a sacred garment. It's your first and last garment; it is what you enter life in and what you depart life with.", author: "Martha Graham" },
  { text: "To insure good health: eat lightly, breathe deeply, live moderately, cultivate cheerfulness.", author: "William Londen" },
  { text: "Preserving health by too severe a rule is a worrisome malady.", author: "François de La Rochefoucauld" },
  { text: "Happiness lies, first of all, in health.", author: "George William Curtis" },
  { text: "The wish for healing has always been half of health.", author: "Lucius Annaeus Seneca" },
  { text: "It is not living that matters, but living rightly.", author: "Socrates" },
  { text: "No man has the right to be an amateur in the matter of physical training. It is a shame for a man to grow old without seeing the beauty and strength of which his body is capable.", author: "Socrates" },
  { text: "Beware the barrenness of a busy life.", author: "Socrates" },
  { text: "An ounce of prevention is worth a pound of cure.", author: "Benjamin Franklin" },
  { text: "Ill-health of body or of mind, is defeat. Health alone is victory. Let all men, if they can manage it, contrive to be healthy.", author: "Thomas Carlyle" },
  { text: "The secret of health for both mind and body is not to mourn for the past, worry about the future, or anticipate troubles, but to live in the present moment wisely and earnestly.", author: "Buddha" },
  { text: "Every human being is the author of his own health or disease.", author: "Buddha" },
  { text: "To enjoy the glow of good health, you must exercise.", author: "Gene Tunney" },
  { text: "The mind and body are not separate. What affects one, affects the other.", author: "Unknown" },
  { text: "Mens sana in corpore sano — a healthy mind in a healthy body.", author: "Juvenal" },
  { text: "Your body hears everything your mind says.", author: "Naomi Judd" },
  { text: "Rest when you're weary. Refresh and renew yourself, your body, your mind, your spirit. Then get back to work.", author: "Ralph Marston" },
  { text: "The doctor of the future will give no medicine, but will interest his patients in the care of the human body, in diet, and in the cause and prevention of disease.", author: "Thomas Edison" },
  { text: "Time and health are two precious assets that we don't recognize and appreciate until they have been depleted.", author: "Denis Waitley" },
  { text: "Physical strength is the most important thing in life. This is not true, but it used to be.", author: "Mark Rippetoe" },
  { text: "Strength is not about how much you can handle before you break. It's about how much you can endure after you've been broken.", author: "Unknown" },
  { text: "Nothing will work unless you do.", author: "Maya Angelou" },
  { text: "A healthy attitude is contagious, but don't wait to catch it from others. Be a carrier.", author: "Tom Stoppard" },
  { text: "Take care of your body with steadfast fidelity. The soul must see through these eyes alone, and if they are dim, the whole world is clouded.", author: "Goethe" },
  { text: "He who enjoys good health is rich, though he knows it not.", author: "Italian Proverb" },
  { text: "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.", author: "Buddha" },
  { text: "A good laugh and a long sleep are the two best cures for anything.", author: "Irish Proverb" },
  { text: "The greatest of follies is to sacrifice health for any other kind of happiness.", author: "Arthur Schopenhauer" },
  { text: "Life is not merely being alive, but being well.", author: "Marcus Valerius Martialis" },
  { text: "Happiness is nothing more than good health and a bad memory.", author: "Albert Schweitzer" },
  { text: "When the body is strong, the mind thinks strong thoughts.", author: "Friedrich Nietzsche" },
  { text: "One must eat to live, not live to eat.", author: "Molière" },
  { text: "Self-discipline is self-love.", author: "Will Durant" },
  { text: "We are lazier in mind than in body.", author: "François de La Rochefoucauld" },
  { text: "Wealth is the ability to fully experience life.", author: "Henry David Thoreau" },
  { text: "Man does not live by bread alone, but also by the sweat of his brow.", author: "Ancient Proverb" },
  { text: "The secret to living well and longer is: eat half, walk double, laugh triple, and love without measure.", author: "Tibetan Proverb" },
  { text: "Without health life is not life; it is only a state of langour and suffering.", author: "François Rabelais" },
  { text: "When wealth is lost, nothing is lost; when health is lost, something is lost; when character is lost, all is lost.", author: "Billy Graham" },
  { text: "Not what we have, but what we enjoy, constitutes our abundance.", author: "Epicurus" },
  { text: "The greatest medicine of all is to teach people how not to need it.", author: "Hippocrates" },
  { text: "Exercise is a celebration of what your body can do. Not a punishment for what you ate.", author: "Unknown" },
  { text: "Movement is a medicine for creating change in a person's physical, emotional, and mental states.", author: "Carol Welch" },
  { text: "You don't get the ass you want by sitting on the one you have.", author: "Unknown" },
  { text: "What we fear doing most is usually what we most need to do.", author: "Ralph Waldo Emerson" },
  { text: "The chains of habit are too light to be felt until they are too heavy to be broken.", author: "Warren Buffett" },
  { text: "We are more often frightened than hurt; and we suffer more in imagination than in reality.", author: "Seneca" },
  { text: "It is not because things are difficult that we do not dare; it is because we do not dare that things are difficult.", author: "Seneca" },
  { text: "Difficulties strengthen the mind, as labour does the body.", author: "Seneca" },
  { text: "Begin at once to live, and count each separate day as a separate life.", author: "Seneca" },
  { text: "Omnia aliena sunt, tempus tantum nostrum — everything else belongs to others; time alone is ours.", author: "Seneca" },
  { text: "He suffers more than necessary, who suffers before it is necessary.", author: "Seneca" },
  { text: "Associate with those who will make a better man of you.", author: "Seneca" },
  { text: "Retire into yourself as much as possible; associate with those who will make a better man of you.", author: "Seneca" },
  { text: "A man is as miserable as he thinks he is.", author: "Seneca" },
  { text: "We should every night call ourselves to an account: What infirmity have I mastered today? What passions opposed? What temptation resisted?", author: "Seneca" },
  { text: "Make the best use of what is in your power, and take the rest as it happens.", author: "Epictetus" },
  { text: "First say to yourself what you would be, then do what you have to do.", author: "Epictetus" },
  { text: "Seek not that the things which happen should happen as you wish; but wish the things which happen to be as they are, and you will have a tranquil flow of life.", author: "Epictetus" },
  { text: "You are not your body and hair-style, but your capacity for choosing well.", author: "Epictetus" },
  { text: "He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has.", author: "Epictetus" },
  { text: "Wealth consists not in having great possessions, but in having few wants.", author: "Epictetus" },
  { text: "The true wealth of a man is the good he does in the world.", author: "Caliph Ali ibn Abi Talib" },
  { text: "If you are distressed by anything external, the pain is not due to the thing itself but to your own estimate of it.", author: "Marcus Aurelius" },
  { text: "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.", author: "Marcus Aurelius" },
  { text: "Accept the things to which fate binds you, and love the people with whom fate brings you together.", author: "Marcus Aurelius" },
  { text: "The object of life is not to be on the side of the majority, but to escape finding oneself in the ranks of the insane.", author: "Marcus Aurelius" },
  { text: "Dwell on the beauty of life. Watch the stars, and see yourself running with them.", author: "Marcus Aurelius" },
  { text: "The best revenge is to be unlike him who performed the injury.", author: "Marcus Aurelius" },
  { text: "How much more grievous are the consequences of anger than the causes of it.", author: "Marcus Aurelius" },
  { text: "Loss is nothing else but change, and change is Nature's delight.", author: "Marcus Aurelius" },
  { text: "Never let the future disturb you. You will meet it, if you have to, with the same weapons of reason which today arm you against the present.", author: "Marcus Aurelius" },
  { text: "Health is a state of complete harmony of the body, mind, and spirit.", author: "B.K.S. Iyengar" },
  { text: "To keep the body in good health is a duty… otherwise we shall not be able to trim the lamp of wisdom.", author: "Buddha" },
  { text: "A fit body, a calm mind, a house full of love. These things cannot be bought — they must be earned.", author: "Naval Ravikant" },
  { text: "Earn with your mind, not your time.", author: "Naval Ravikant" },
  { text: "The purpose of life is to be defeated by greater and greater things.", author: "Rainer Maria Rilke" },
  { text: "One cannot think well, love well, sleep well, if one has not dined well.", author: "Virginia Woolf" },
  { text: "It is health and vigour that drive courage and enterprise.", author: "Machiavelli" },
  { text: "The higher your energy level, the more efficient your body. The more efficient your body, the better you feel and the more you will use your talent to produce outstanding results.", author: "Tony Robbins" },
  { text: "Your body is a reflection of your lifestyle.", author: "Unknown" },
  { text: "Eat well, move daily, hydrate often, sleep enough, repeat.", author: "Unknown" },
  { text: "The difference between a successful person and others is not lack of strength, not lack of knowledge, but rather a lack of will.", author: "Vince Lombardi" },
  { text: "The good life is one inspired by love and guided by knowledge.", author: "Bertrand Russell" },
  { text: "Invest in yourself. Your career is the engine of your wealth.", author: "Paul Clitheroe" },
  { text: "The richest person is not the one who has the most, but the one who needs the least.", author: "Unknown" },
  { text: "When the well is dry, we know the worth of water.", author: "Benjamin Franklin" },
  { text: "Take care of your body, and your body will take care of you.", author: "Unknown" },
  { text: "A man too busy to take care of his health is like a mechanic too busy to take care of his tools.", author: "Spanish Proverb" },
]

export function getDailyQuote(): Quote {
  const dayIndex = Math.floor(Date.now() / 86_400_000)
  return QUOTES[dayIndex % QUOTES.length]
}
