export interface Quote {
  text: string
  author: string
}

export const QUOTES: Quote[] = [
  { text: "You do not rise to the level of your goals. You fall to the level of your systems.", author: "James Clear" },
  { text: "Every action you take is a vote for the type of person you wish to become.", author: "James Clear" },
  { text: "Success is the product of daily habits — not once-in-a-lifetime transformations.", author: "James Clear" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle" },
  { text: "Small daily improvements are the key to staggering long-term results.", author: "Robin Sharma" },
  { text: "The first wealth is health.", author: "Ralph Waldo Emerson" },
  { text: "Take care of your body. It's the only place you have to live.", author: "Jim Rohn" },
  { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
  { text: "We must all suffer from one of two pains: the pain of discipline or the pain of regret.", author: "Jim Rohn" },
  { text: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun" },
  { text: "The groundwork of all happiness is health.", author: "Leigh Hunt" },
  { text: "The greatest wealth is health.", author: "Virgil" },
  { text: "Health is not valued until sickness comes.", author: "Thomas Fuller" },
  { text: "Health is like money — we never have a true idea of its value until we lose it.", author: "Josh Billings" },
  { text: "A healthy outside starts from the inside.", author: "Robert Urich" },
  { text: "To keep the body in good health is a duty, otherwise we shall not be able to keep our mind strong and clear.", author: "Buddha" },
  { text: "Your health is an investment, not an expense.", author: "Unknown" },
  { text: "Physical fitness is not only one of the most important keys to a healthy body, it is the basis of dynamic and creative intellectual activity.", author: "John F. Kennedy" },
  { text: "Physical fitness is the basis of all other forms of excellence.", author: "John F. Kennedy" },
  { text: "What gets measured gets managed.", author: "Peter Drucker" },
  { text: "Without data, you're just another person with an opinion.", author: "W. Edwards Deming" },
  { text: "Continuous improvement is better than delayed perfection.", author: "Mark Twain" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "Measure what is measurable, and make measurable what is not so.", author: "Galileo Galilei" },
  { text: "I hated every minute of training, but I said, 'Don't quit. Suffer now and live the rest of your life as a champion.'", author: "Muhammad Ali" },
  { text: "Champions aren't made in gyms. Champions are made from something they have deep inside them.", author: "Muhammad Ali" },
  { text: "The fight is won or lost far away from witnesses — behind the lines, in the gym, and out there on the road.", author: "Muhammad Ali" },
  { text: "Float like a butterfly, sting like a bee.", author: "Muhammad Ali" },
  { text: "If you always put limits on everything you do, physical or anything else, it will spread into your work and into your life. There are no limits. There are only plateaus.", author: "Bruce Lee" },
  { text: "Do not pray for an easy life, pray for the strength to endure a difficult one.", author: "Bruce Lee" },
  { text: "The successful warrior is the average man, with laser-like focus.", author: "Bruce Lee" },
  { text: "Be water, my friend.", author: "Bruce Lee" },
  { text: "The last three or four reps is what makes the muscle grow. This area of pain divides a champion from someone who is not a champion.", author: "Arnold Schwarzenegger" },
  { text: "The mind is the limit. As long as the mind can envision the fact that you can do something, you can do it.", author: "Arnold Schwarzenegger" },
  { text: "I've missed more than 9,000 shots in my career. I've failed over and over again in my life. And that is why I succeed.", author: "Michael Jordan" },
  { text: "Some people want it to happen, some wish it would happen, others make it happen.", author: "Michael Jordan" },
  { text: "You must expect great things of yourself before you can do them.", author: "Michael Jordan" },
  { text: "Obstacles don't have to stop you. If you run into a wall, don't turn around and give up.", author: "Michael Jordan" },
  { text: "Hard work beats talent when talent doesn't work hard.", author: "Tim Notke" },
  { text: "Success is never owned. It is only rented, and the rent is due every day.", author: "Rory Vaden" },
  { text: "If it doesn't challenge you, it doesn't change you.", author: "Fred DeVito" },
  { text: "It's not whether you get knocked down, it's whether you get up.", author: "Vince Lombardi" },
  { text: "Winners never quit and quitters never win.", author: "Vince Lombardi" },
  { text: "Make each day your masterpiece.", author: "John Wooden" },
  { text: "Success is not final; failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { text: "If you're going through hell, keep going.", author: "Winston Churchill" },
  { text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
  { text: "Well done is better than well said.", author: "Benjamin Franklin" },
  { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
  { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { text: "Do not wait; the time will never be 'just right.' Start where you stand.", author: "Napoleon Hill" },
  { text: "Strength does not come from physical capacity. It comes from an indomitable will.", author: "Mahatma Gandhi" },
  { text: "The more you sweat in training, the less you bleed in battle.", author: "Richard Marcinko" },
  { text: "Ability is what you're capable of doing. Motivation determines what you do. Attitude determines how well you do it.", author: "Lou Holtz" },
  { text: "To enjoy the glow of good health, you must exercise.", author: "Gene Tunney" },
  { text: "Tough times never last, but tough people do.", author: "Robert H. Schuller" },
  { text: "In training, you listen to your body. In competition, you tell your body to shut up.", author: "Rich Froning" },
  { text: "You have to push past your perceived limits, push past that point you thought was as far as you can go.", author: "Drew Brees" },
  { text: "Strength is not just about lifting weights. It's about lifting yourself up every single day.", author: "Unknown" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { text: "Strive for progress, not perfection.", author: "Unknown" },
  { text: "A year from now you'll wish you had started today.", author: "Karen Lamb" },
  { text: "Your body can stand almost anything. It's your mind that you have to convince.", author: "Unknown" },
  { text: "The only bad workout is the one that didn't happen.", author: "Unknown" },
  { text: "Results happen over time, not overnight. Work hard, stay consistent, and be patient.", author: "Unknown" },
  { text: "You're only one workout away from a good mood.", author: "Unknown" },
  { text: "Do something today that your future self will thank you for.", author: "Sean Patrick Flanery" },
  { text: "The body achieves what the mind believes.", author: "Unknown" },
  { text: "The pain you feel today will be the strength you feel tomorrow.", author: "Unknown" },
  { text: "One rep at a time. One session at a time. One day at a time.", author: "Unknown" },
  { text: "It never gets easier. You just get better.", author: "Unknown" },
  { text: "The first step to getting somewhere is to decide you're not going to stay where you are.", author: "J.P. Morgan" },
  { text: "We become what we think about most of the time.", author: "Earl Nightingale" },
  { text: "Showing up today is already a win.", author: "Unknown" },
  { text: "The secret is not to sprint and rest. It's to pace yourself and keep going.", author: "Unknown" },
  { text: "Be patient with yourself. Self-growth is tender; it's holy ground.", author: "Stephen Covey" },
  { text: "You don't always get what you wish for. You get what you work for.", author: "Unknown" },
  { text: "Pain is temporary. Quitting lasts forever.", author: "Lance Armstrong" },
  { text: "If something stands between you and your success, move it. Never be denied.", author: "Dwayne Johnson" },
  { text: "Wake up determined. Go to bed satisfied.", author: "Dwayne Johnson" },
  { text: "Blood, sweat, and respect. First two you give. Last one you earn.", author: "Dwayne Johnson" },
  { text: "Success isn't always about greatness. It's about consistency.", author: "Dwayne Johnson" },
  { text: "You have to remember something: everybody pities the weak; jealousy you have to earn.", author: "Arnold Schwarzenegger" },
  { text: "For me, life is continuously being hungry. The meaning of life is not simply to exist, to survive, but to move ahead.", author: "Arnold Schwarzenegger" },
  { text: "I don't stop when I'm tired. I stop when I'm done.", author: "David Goggins" },
  { text: "The most important conversation is the one you have with yourself.", author: "David Goggins" },
  { text: "You are in danger of living a life so comfortable and soft that you will die without ever realizing your true potential.", author: "David Goggins" },
  { text: "Suffer the pain of discipline or suffer the pain of regret.", author: "David Goggins" },
  { text: "Waste no more time arguing about what a good man should be. Be one.", author: "Marcus Aurelius" },
  { text: "You have power over your mind — not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius" },
  { text: "The impediment to action advances action. What stands in the way becomes the way.", author: "Marcus Aurelius" },
  { text: "Confine yourself to the present.", author: "Marcus Aurelius" },
  { text: "The quality of your practice is ultimately measured by its effect on the quality of your life.", author: "Unknown" },
  { text: "Champions do not become champions when they win the event, but in the hours, weeks, months and years they spend preparing for it.", author: "T. Alan Armstrong" },
  { text: "There are no shortcuts. The fact that a shortcut is important to you means that the outcome is more important to you than the journey.", author: "Unknown" },
  { text: "Obsessed is a word the lazy use to describe the dedicated.", author: "Unknown" },
  { text: "Train like an athlete, eat like a nutritionist, sleep like a baby, win like a champion.", author: "Unknown" },
  { text: "Your future self is watching you right now through your memories. Make it worth watching.", author: "Aubrey de Grey" },
  { text: "Don't wish it were easier. Wish you were better.", author: "Jim Rohn" },
  { text: "The difference between who you are and who you want to be is what you do.", author: "Unknown" },
  { text: "Eighty percent of success is showing up.", author: "Woody Allen" },
]

export function getDailyQuote(): Quote {
  const dayIndex = Math.floor(Date.now() / 86_400_000)
  return QUOTES[dayIndex % QUOTES.length]
}
